name: CD Pipeline
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
        - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: sudo docker pull hellen0123/pocurq:latest
    - name: Delete Old docker container
      run: sudo docker rm -f pocurq || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name pocurq hellen0123/pocurq
